define_directive {n:work.top|outBit1} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_outBit1}
define_directive {n:work.top|dataAXI} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_dataAXI}
define_directive {n:work.top|readyAXI} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_readyAXI}
define_directive {n:work.top|outBit3} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_outBit3}
define_directive {n:work.top|outBit2} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_outBit2}
define_directive {n:work.top|valid} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_valid}
define_directive {n:work.top|validAXI} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_validAXI}
define_directive {n:work.top|clk} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_clk}
define_directive {n:work.top|outBit4} {ident_debug} {PURPOSE=IDENTIFY,TAG=ident_ihs_outBit4}
